---
- name: alerting rules file
  template:
    src: "alert.rules.j2"
    dest: "{{ prometheus_config_dir }}/rules/ansible_managed.rules"
    owner: root
    group: prometheus
    mode: 0640
    validate: "{{ _prometheus_binary_install_dir }}/promtool check rules %s"
  when:
    - prometheus_alert_rules != []
  notify:
    - reload prometheus

- name: Change rules files permissions
  file:
    path: "{{ prometheus_config_dir }}/rules/"
    state: directory
    recurse: yes
    owner: root
    group: prometheus
    mode: u=rwX,g=rX,o=rx

- name: configure prometheus
  template:
    src: "{{ prometheus_config_file }}"
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    force: true
    owner: root
    group: prometheus
    mode: 0640
    validate: "{{ _prometheus_binary_install_dir }}/promtool check config %s"
  notify:
    - reload prometheus

- name: configure prometheus static targets
  copy:
    content: |
      #jinja2: lstrip_blocks: True
      {{ item.value | to_nice_yaml(indent=2) }}
    dest: "{{ prometheus_config_dir }}/file_sd/{{ item.key }}.yml"
    force: true
    owner: root
    group: prometheus
    mode: 0640
  with_dict: "{{ prometheus_targets }}"
  when: prometheus_targets != {}

- name: Sync prometheus custom static targets
  synchronize:
    src: "{{ prometheus_static_targets_path }}"
    dest: "{{ prometheus_config_dir }}/file_sd/"
    delete: yes
    rsync_opts:
      - "--exclude=.getkeep"
  notify:
    - reload prometheus

- name: Change prometheus static targets
  file:
    path: "{{ prometheus_config_dir }}/file_sd/"
    state: directory
    recurse: yes
    owner: root
    group: prometheus
    mode: u=rwX,g=rX,o=rx
