---
- name: Install nginx proxy
  package:
    name: nginx
    state: present

- name: Copy ssl cert file
  copy:
    src: "{{ ssl_cert_path }}.crt"
    dest: "/etc/ssl/{{ ssl_cert_filename }}.crt"
    owner: root
    group: root
    mode: '0644'

- name: Copy ssl key file
  copy:
    src: "{{ ssl_cert_path }}.key"
    dest: "/etc/ssl/{{ ssl_cert_filename }}.key"
    owner: root
    group: root
    mode: '0644'

- name: htpasswd basic auth
  htpasswd:
    path: /etc/nginx/.htpasswd
    name: prometheus
    password: "{{ prometheus_basic_auth_password }}"
    owner: root
    group: www-data
    mode: 0640
  become: true
  when: prometheus_basic_auth_enabled is sameas true
  notify:
    - restart nginx

- name: Create vhost file for web ui
  template:
    src: prometheus.conf.j2
    dest: /etc/nginx/sites-available/prometheus.conf
    mode: '0644' 
  notify:
    - reload nginx

- name: make sure default site is desabled
  file:
    state: absent
    path: /etc/nginx/sites-enabled/default
  notify:
    - reload nginx

- name: Create links for sites-enabled
  file:
    state: link
    src: /etc/nginx/sites-available/prometheus.conf
    dest: /etc/nginx/sites-enabled/prometheus.conf
  notify:
    - reload nginx
